### ISSUE TITLE
Undefined is not an object (evaluating 'this.props.preview') [Android]

### ISSUE THREAD

**Issue by alanlanglois** [wcandillon/react-native-expo-image-cache#10]
![image](https://user-images.githubusercontent.com/712986/35692283-38f8aa8a-077b-11e8-8e3a-53f79fbe05a0.png)

Thanks for your awesome lib, it works pretty well!

However I get this error sometimes. I'm testing my app super fast, it might be related. 
My guess is that the component is maybe removed before download is finished.

I'll dig a little more and let you know if I find something. 

Cheers,

**Comment by alanlanglois** [comment]
Adding this in Image.js line 51 seems to do the job : 

`if(this.props == undefined ) return;`

**Comment by alanlanglois** [comment]
It does not really fix it. At least I don't get the redscreen anymore, but now the pictures is not displayed with a full opacity. 
I'm suspecting the animation to causes bugs, maybe we should cancel/stop it when receiving  componentWillUnmount()?

**Comment by wcandillon** [comment]
@alanlanglois Thank you so much! I never had the error myself but some user have reported it. Do you think it can be the animation? I guess it wouldn't hurt to do more clean up on `unmount()`. It could be also `onLoadEnd()` called when the component is unmounted.

**Comment by alanlanglois** [comment]
@wcandillon : Thanks for the fast reply :)
I'm kind of new in the whole React Native world, but my guess is that the `onLoadEnd` is called when the component is unmounted (that would explain why this.props is undefined) AND/OR that the animation is completed while the component is already unmounted (or being unmounted)

**Comment by wcandillon** [comment]
@alanlanglois You are 100% correct, I'll try to push a fix for it asap.

**Comment by alanlanglois** [comment]
@wcandillon Looking the RN doc, it seems like there is no way to cancel an Image loading in the RN Image component... that would have been very convenient :)
I'd say adding a variable `isMounted` could be a quick fix to implement.

Sounds like we are not alone!
 - https://github.com/facebook/react/issues/2787#issuecomment-304485634
 - https://github.com/facebook/react-native/issues/12152
 :)

**Comment by wcandillon** [comment]
Woah thank you so much for your support on that issue!

**Comment by wcandillon** [comment]
Feel free to re-open is needed :)

**Comment by alanlanglois** [comment]
@wcandillon it's fixed! 

But'ill maybe open a new one though :)

I got the picture loaded, but sometimes (and it's kind of random), the picture won't appear fully oppacified, if I go back wait a little a try again it will eventually work as expected... or not, until it works again, and doesn't again. 
Can't reproduce on iOS, it seems to be Android specific.
I'll try to find why and how to explain. 

Thanks for the fix!

Cheers,
