### ISSUE TITLE
CacheManager - Cache validation

### ISSUE THREAD

**Issue by kriskate** [wcandillon/react-native-expo-image-cache#104]
First of all, great idea. 
I had issues relying on Image.prefetch so your approach to the caching situation makes life a bit easier, although fetching multiple data files/ images at once (via Promise.all) React Native might make the app unresponsive. Using something like [es6-promise-pool](https://github.com/timdp/es6-promise-pool) gets the job done regardless of how many Promises you generate.
Image.prefetch doesn't have this issue, as it most probably uses native code to do the fetching.

What would be really useful (in my case at least, where I pre-cache around 1000 images), would be the ability to check if the image is cached, but don't force-cache it as the check happens.

So something like:
```
// will not trigger image download
const {exists} = CacheManager.getInfo('image-url');
```

*What I'm trying to do is check if all the images are cached, and if not, ask the user if he authorises the app to download the missing images.*

**Comment by kriskate** [comment]
my bad - did not realise that's what you get when calling ```get```, and that ```getPath``` makes the actual download happen

**Comment by nandorojo** [comment]
Have you tried this?

```javascript
const get = async (remoteUri) => {
   const path = await CacheManager.get(remoteUri).getPath()
   console.log(path)
}

```

**Comment by kriskate** [comment]
Yes, the issue is that I want to check if they are cached, without actually starting to cache them.
As I rembember, ```CacheManager.get()``` would immediately start caching.

Eventually, React Native implemented ```Image.queryCache``` which would fit my needs.

Thanks!
