### ISSUE TITLE
Expo V33.0.0 FileSystem, BlurView

### ISSUE THREAD

**Issue by Silvobe** [wcandillon/react-native-expo-image-cache#107]
Hi, I have a problem with react-native-expo-image-cache since Expo upgraded to 33.0. Now FileSystem and BlurView are imported separately.
How can I continue to use react-native-expo-image-cache? It's a good module for me.

**Comment by wcandillon** [comment]
I will update the package in the next few days. Thank you for your patience.

**Comment by wcandillon** [comment]
fixed in v4.0.0 🙌🏻
