### ISSUE TITLE
Upgrading to the version 4.0.3 error to resolve module

### ISSUE THREAD

**Issue by mgcostaParedes** [wcandillon/react-native-expo-image-cache#113]
After upgrading the package to the version 4.0.3, i get the following error at starting the packager:

While trying to resolve module `react-native-expo-image-cache` from file `c:\Projects\app\src\components\common\UI\avatar.js`, the package `c:\Projects\app\node_modules\react-native-expo-image-cache\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`c:\Projects\app\node_modules\react-native-expo-image-cache\dist\src\index.js`. Indeed, none of these files exist

Is this related to the typescript? what should i do? ( i already tried to remove node_modules, reinstall)

**Comment by wcandillon** [comment]
sorry about that 😅 this is fixed in `4.0.4`
