### ISSUE TITLE
Unable to resolve "@unimodules/core" from "node_modules/expo-blur/build/BlurView.ios.js"

### ISSUE THREAD

**Issue by esdrasevt** [wcandillon/react-native-expo-image-cache#119]
I'm getting this error:
`Unable to resolve "@unimodules/core" from "node_modules/expo-blur/build/BlurView.ios.js"`

Fully managed Expo project, not ejected, running Expo SDK 32.
I've created a separate branch and updated expo sdk to 33 and it works fine. 
The thing is, most of our live apps are still running expo sdk 32 and it will be a while until we get all of them updated, and I really wanted to start using this library.

Anybody has any idea on how to solve this?

I've already tried updating both node and npm, deleting node_modules and running npm install again, removing the expo app from the simulator and running expo again to get the updated app, none of these solved the problem.

Before that error, I was getting this error :
`Unable to resolve "expo-blur" from "node_modules/react-native-expo-image-cache/dist/module/Image.js"`

Then, I manually installed expo-blur with npm, and started getting the error mentioned in the title. Maybe those are related? I don't know.

Any help is appreciated.

**Comment by wcandillon** [comment]
I'm so sorry to read that, unfortunately we don't support expo sdk32 anymore but you can downgrade to a version that would work great for you: `3.2.0`. Please feel free to reopen this issue if needed.
