### ISSUE TITLE
[Android] - Image not displayed at full opacity

### ISSUE THREAD

**Issue by alanlanglois** [wcandillon/react-native-expo-image-cache#15]
Version: **1.0.6**

The animation bringing the Image to full opacity doesn't seem to start/finish in some cases. 

I've notice it happen the first time I load an image (after the app just opened). 
If I load another page and reload the page it sometimes work and display the animation at full opacity (anmation appear to be working).
Here how it looks when not properly displayed 
![image](https://user-images.githubusercontent.com/712986/35769301-41439c6a-0909-11e8-80e4-31267518c5cd.png)

And here when it's loaded and displayed as it should: 
![image](https://user-images.githubusercontent.com/712986/35769430-1e1de8c4-090b-11e8-9946-13e1ab4fa8d7.png)

I guess, there is a problem with the mounted var you added and the condition.

**Comment by wcandillon** [comment]
I’m experiencing the same issue as well 😅 will take a look. Thanks for
your help, really appreciate it. It’s nice to have extra help with the
testing.

**Comment by wcandillon** [comment]
I think we realized fix it this time, the previous was completely misguided 😅

**Comment by nsdub** [comment]
This issue persists in version 4.1.0

**Comment by elie-chaaban** [comment]
this issue still exists in 4.1.0, how to fix?
