### ISSUE TITLE
Facebook profile images do not render

### ISSUE THREAD

**Issue by Sonblind** [wcandillon/react-native-expo-image-cache#17]
I'm passing `https://graph.facebook.com/USER_ID/picture?type=large` to the `uri` prop, but nothing is showing up. It works fine with other urls

**Comment by wcandillon** [comment]
Could it be the CSS applied to the component that makes it not wonder? Or does it work fine with another image URL?

**Comment by Sonblind** [comment]
It works fine with other image URLs

**Comment by wcandillon** [comment]
I just realized that there is a bug where images with no filename extension are not working. I will fix it asap. Thanks for reporting this.

**Comment by Sonblind** [comment]
ok, thanks! @wcandillon
