### ISSUE TITLE
"The Expo SDK requires Expo to run" red screen

### ISSUE THREAD

**Issue by brownieboy** [wcandillon/react-native-expo-image-cache#19]
Does this module only work with Expo apps, or apps that were once on Expo, but subsequently ejected?

I ask because I'm trying to use the module against an app that has never been on Expo, and it's red screening with the following error:
> The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo

I've added Expo as dependency, `yarn add expo`.  Is there something else that I need to do?

**Comment by wcandillon** [comment]
@brownieboy It looks like you need to add expokit to your project: https://docs.expo.io/versions/latest/guides/expokit.html. Please feel free to reopen if needed.

**Comment by brownieboy** [comment]
Thank you, @wcandillon.

From that guide:

> There are two ways to get an ExpoKit project:
> 
> - Create a pure-JS project in XDE, then use exp detach to add ExpoKit.
> - Create an app with create-react-native-app, then choose “eject with ExpoKit”.

So the answer to my question would appear to be "no".  You have to start with Expo in some form.  No easy way of retrospectively adding ExpoKit to an existing project.

**Comment by wcandillon** [comment]
@brownieboy That's a good questions that you should ask on https://forums.expo.io/. It should be possible to install it just like any other iOS and Android native dependencies. But there are probably some pitfalls to be aware of.

**Comment by brownieboy** [comment]
Thanks, @wcandillon.

Looks like there's a few threads on this topic over there already: https://forums.expo.io/search?q=existing%20project.  And the answers are always to create a new, blank Expo project and then copy your source code over.

There was an `exp convert` command available for this purpose at one point, it seems.  But that "is temporarily under maintenance and not available" as of August 2017.

I'll stick with with your React Native Image Cache for now.  It's still doing the job for me, despite its Deprecated status, and the missing Maintainer on the React Native Fetch Blob dependency.

**Comment by wcandillon** [comment]
@brownieboy sorry to hear that you're having all this trouble. If you are having issues with react-native-image-cache, maybe consider using this implementation and replace the Expo.FileSystem dependency with something else like react-native-fs

**Comment by RishabhTayal** [comment]
@brownieboy did you find solution for this issue?
