### ISSUE TITLE
Why using autobind-decorator ?

### ISSUE THREAD

**Issue by LouisJS** [wcandillon/react-native-expo-image-cache#22]
Couldn't you use ES6 arrow function in your class ?

https://stackoverflow.com/questions/32192682/react-js-es6-avoid-binding-this-to-every-method

**Comment by wcandillon** [comment]
good point 👍🏻

**Comment by LouisJS** [comment]
This has nothing to do with the 'License' PR i've made.
Shouldn't this Issue be set as 'In Progress' ?

**Comment by wcandillon** [comment]
I added the change to the integration branch as well

**Comment by LouisJS** [comment]
Oh i see. Great 🌟
