### ISSUE TITLE
resizeMode

### ISSUE THREAD

**Issue by BealiF** [wcandillon/react-native-expo-image-cache#35]
Hi,
It would be useful to be able to change the resizeMode of the picture.
The 'contain' mode is really usefull for a gallery of different ratio pictures for example.  ;-) 
Thank you for this simple and strong component !

**Comment by wcandillon** [comment]
Should be fixed now :) Feel free to re-open if it doesn't work.

**Comment by BealiF** [comment]
Hello, thank you , 
I was unable to make it work ,I use prop resizeMode="contain" on your comp, but nothing changed.
I'm a beginner so I am not sure but the only thing I found :
I updated my npm package to 1.0.0 but it seems to not have the "otherprops" changes.
Do you think that can come from me ? I don't know were to look now.

**Comment by wcandillon** [comment]
Can you try with react-native-expo-image-cache@1.1.0?

**Comment by BealiF** [comment]
oups sorry my writting mistake , that the version I use.

**Comment by wcandillon** [comment]
@BealiF Thanks for letting me know, I will do more testing.

**Comment by LouisJS** [comment]
Doesn't seems to work to me.

I did:

```
<Image
     style={style.image}
     resizeMode={"center"}
     {...{
        preview: product.image_thumbnail_url,
        uri: product.image_url
     }}
/>
```

**Comment by wcandillon** [comment]
Not sure what went wrong in the package publishing 😳 Sorry for the trouble, it should work nicely in `1.1.1` now: https://www.dropbox.com/s/97gtjkxredegl1y/resizeMode.mov?dl=0.

**Comment by LouisJS** [comment]
Thanks for the quick update @wcandillon !
Absolutely no problem 😄

**Comment by BealiF** [comment]
Work perfectly here too , Thank you !

**Comment by Developer-Rahmah** [comment]
you can do like this:
`<Image
          {...{ resizeMode:'contain' }}
          uri={image}
          onError={onImageLoadingError}
          style={style}
        />`
