### ISSUE TITLE
clearCache Feature

### ISSUE THREAD

**Issue by LouisJS** [wcandillon/react-native-expo-image-cache#43]
Sometimes, it happens that while using : 

```
import {Image} from "react-native-expo-image-cache";

const preview = "url_of_my_preview_image.png";
const uri = "url_of_my_full_scaled_image.png";
<Image style={{ height: 100, width: 100 }} {...{preview, uri}} />
```

It happens sometimes for no reason that my `uri` is not loaded and only the preview is available. So it renders a blurred image only. (i'm trying my app on three real devices and on iOS simulator when loading 50+ images. Sometimes it happens, most of the time it doesn't.)

Would it be possible to force to remove some URI from the cache so it can be re-uploaded.
An example of implementation, on a flatlist, onRefresh, clean the image Cache and reload the `Image`. Or inside a Card, add a button reload to force the retrieve of an Image.

Thanks for your help

**Comment by dacastro4** [comment]
@wcandillon What if I want to delete a single cached file? Is there an option for that?
