### ISSUE TITLE
Having trouble getting images to show

### ISSUE THREAD

**Issue by mrnkr** [wcandillon/react-native-expo-image-cache#53]
My environment:
React: 16.2.0
React Native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz
Expo: 25.0.0
This lib: 2.0.1

Hello!

I only tested this on iOS and the issue is just as the title says. The funny thing is that the same code works on version 1.0.6 of this lib. Such code is the same as the demo usage available on the README.
Any advise?

Thanks a lot!

**Comment by wcandillon** [comment]
@mrnkr I upgraded an existing project to `2.0.1` and I'm not getting issues. Could you provide me more information, like a standalone code snippet so I could try to reproduce the issue on my side?

**Comment by mrnkr** [comment]
Thank you for the quick reply!

I was just doing some more testing, making sure I wasn't just making any silly mistakes, but indeed there are some issues, probably my fault if you are not getting them... Anyway none of them trigger any warning or error message whatsoever. I was able to isolate the issue to Images with a remote uri, local files seem to work just fine (tested images taken by the camera) and so do previews.

However, right before writing this I had an issue showing local images as well... The image taken by the camera, which I show a preview of, wasn't showing on iOS, the view was rendering but not the image...

I made this repo with the code that has the issue, I tried to leave comments explaining the individual problems and the code seems quite self explainatory but basically the errors seem to be around my Message and my MessageInput components, the Preview component has the same error as Message. If there is anything I can do to make this any less time consuming please let me know!

The repo: https://github.com/mrnkr/my-chat

I'll get some sleep and then I'll see if I can make any progress, I'll get back to you if I do!
Thank you so much!

**Comment by wcandillon** [comment]
@mrnkr Thank you for your message, I discover a substancial bug in `2.0.1.` that affects fresh installation of the package. I think it is the issue you are experiencing. Should be fixed soon. I will keep you posted, sorry for the inconvenience and thanks for your patience..

**Comment by mrnkr** [comment]
Wow, that was quick hahah. Don't worry, it happens! Thank you for the great work

**Comment by wcandillon** [comment]
can you try with `2.0.2`?

**Comment by mrnkr** [comment]
Just tried it and it was flawless :)

Again, thank you so much and have a great day!!

**Comment by wcandillon** [comment]
Woah awesome! Sorry for inconvenience.
