### ISSUE TITLE
`preview` not resize with require('image/path')

### ISSUE THREAD

**Issue by kenhuang** [wcandillon/react-native-expo-image-cache#59]
Thanks for this awesome library!

When I try `preview` with the local image face the following issue, image fetch with `uri` seems ok:
![screen shot 2018-04-08 at 8 42 18 pm](https://user-images.githubusercontent.com/205194/38465241-784d4198-3b6d-11e8-9d30-2c8d5ef38975.png)

Version: 2.0.2

```
        if (images && images[0]) {
            return <Image resizeMode={'stretch'} style={{ height: 100, width: 100 }} {...{ uri: images[0].imgUrl }} />;
        } else {
            return (
                <Image
                    resizeMode={'stretch'}
                    style={{ height: 100, width: 100 }}
                    {...{ preview: require('../../assets/images/mini.jpg') }}
                />
            );
        }
```

**Comment by wcandillon** [comment]
@kenhuang is the issue that you would like `resizeMode` to be applied to the preview image as well? This is not done at the moment.

**Comment by jhalborg** [comment]
@wcandillon - I think it would be the most intuitive if `resizeMode` applied to both preview and full uri

**Comment by brendan-jefferis** [comment]
Preview `resizeMode` is currently set to `'cover'` and ignores props

PR that fixes it here https://github.com/wcandillon/react-native-expo-image-cache/pull/101
