### ISSUE TITLE
It is not fixed PR#61(Revert use of resumableDownload)

### ISSUE THREAD

**Issue by watanabeyu** [wcandillon/react-native-expo-image-cache#62]
Hi
I use this library for caching gif.
But warning(There is no download object with UUID) appeared on v3.0.0.
So I saw [PR#61](https://github.com/wcandillon/react-native-expo-image-cache/pull/61), and update to v3.0.1, but the warning appeared yet.

Maybe, DownloadResumable class([expo-sdk/FileSystem](https://github.com/expo/expo-sdk/blob/master/src/FileSystem.js#L108)) is still called.

Please fix this warning.

**Comment by watanabeyu** [comment]
Maybe, files up to npm are not compiled.
Please compile files and re-publish to npm.

**Comment by wcandillon** [comment]
yes 😅🙈Can you try with `3.0.2`?

**Comment by wcandillon** [comment]
Please re-open if it doesn't work with `3.0.2`
