### ISSUE TITLE
Warning: Failed prop type: Invalid prop `source` supplied to `Image`.

### ISSUE THREAD

**Issue by kevinscience** [wcandillon/react-native-expo-image-cache#69]
Hi, this repo is really a great improvement for Expo Images.
But this warning raised recently.

```
<CacheImage
        preview={getAvatarPlaceholder}
        uri={data.creator.photoURL}
        style={styles.userPic}/>

export const getAvatarPlaceholder = () => {
    return require('../assets/images/avatar-placeholder.png');
};


Warning: Failed prop type: Invalid prop `source` supplied to `Image`.
    in Image (at Image.js:92)
    in Image (at DiscoverScreen.js:347)
```

In output, it states that the error happens in Image.js:92 which is about preview.

**Comment by wcandillon** [comment]
@kevinscience I haven't seen this warning yet, what do you think is the issue?

**Comment by kevinscience** [comment]
Thank you for quick replying!
After I make this change `preview={require('../../assets/images/avatar-placeholder.png')}`
instead of `preview={getAvatarPlaceholder}`, the warning went away.

But I have a new problem here.
```
<CacheImage
        preview={require('../../assets/images/avatar-placeholder.png')}
        uri={selectedMeetData.creator.photoURL}
        style={styles.userPic}/>

const styles = StyleSheet.create({
    userPic: {
        height: 45,
        width: 45,
        borderRadius: 22,
        marginRight: 10,
        marginTop:10,
    },
}

```
<img width="364" alt="screen shot 2018-05-31 at 4 01 13 am" src="https://user-images.githubusercontent.com/19722517/40770115-c72c1aa8-6487-11e8-8701-af1331df84b8.png">

**Comment by wcandillon** [comment]
What seems to be the issue?

**Comment by kevinscience** [comment]
The preview avatar placeholder image(grey one) with wrong size laying at background of the actual image.

**Comment by matteocollina** [comment]
any news ?

**Comment by brendan-jefferis** [comment]
If you're passing a uri string, you'll want to replace

`preview={preview}`

with

`preview={{ uri: preview }}`

Relevant PR here https://github.com/wcandillon/react-native-expo-image-cache/pull/102

**Comment by kriskate** [comment]
The issue might be regarding attributing locally required images as a source for <Image>
```
<Image source={require('my_image.png')} />
```
I had to recourse to creating my own HOC, which supports both local images, and CacheManager images, as I'm using a mixture of both local and remote images.

**Comment by Diegolaquino** [comment]
> If you're passing a uri string, you'll want to replace
> 
> `preview={preview}`
> 
> with
> 
> `preview={{ uri: preview }}`
> 
> Relevant PR here #102

Thanks.

**Comment by Mehebbet13** [comment]
> If you're passing a uri string, you'll want to replace
> 
> `preview={preview}`
> 
> with
> 
> `preview={{ uri: preview }}`
> 
> Relevant PR here #102

thanksss, It works now

**Comment by MarcosFF1996** [comment]
> Se você estiver passando uma string de uri, substitua
> 
> `preview={preview}`
> 
> com
> 
> `preview={{ uri: preview }}`
> 
> Relações Públicas relevantes aqui [# 102](https://github.com/wcandillon/react-native-expo-image-cache/pull/102)

It worked for me, thanks!

**Comment by MarcosFF1996** [comment]
> If you're passing a uri string, you'll want to replace
> 
> `preview={preview}`
> 
> with
> 
> `preview={{ uri: preview }}`
> 
> Relevant PR here #102

It worked for me, thanks!
