### ISSUE TITLE
possible to support tintColor?

### ISSUE THREAD

**Issue by hgoldwire** [wcandillon/react-native-expo-image-cache#70]
Similar to https://github.com/wcandillon/react-native-expo-image-cache/issues/35 (resizeMode), it would be great if we could support tintColor.  

tintColor is an RNImage-specific style prop, and not a valid style prop for normal Views.  So we'd need to stuff it into computedStyle for RNImage, and be sure _not_ pass it to the outermost view's style.

I can make a PR if it would be helpful.

**Comment by dimoFeeld** [comment]
I am having build issues when installing from my fork. I guess there are some special distro scripts that don't run properly. Will be happy if someone can test the PR with the correct scripts in place. 

Note: I am a newbie developer so don't trust me 💃
